import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/header";

const jetBrainsMono = JetBrains_Mono({
  variable: "--jet",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.className} antialiased`}>
        <main className="w-full max-w-5xl min-h-dvh p-6 place-self-center">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
